### ISSUE TITLE
Header ception

### ISSUE THREAD

**Issue by DreggHunShot** [CTFNote/frontend#1]
When opening an event, clicking on a task takes me back to the main page (the event has not started yet, maybe that is why?). After this I can click on an event again, which will open, and it also opens a 2nd header. I can click on tasks again, and when i try to open a task, the app will get stuck in an infinite loading cycle.

![ctf_note double header](https://user-images.githubusercontent.com/54242106/99817025-ae7f0180-2b4c-11eb-9cae-522603677859.png)

**Comment by theS1LV3R** [comment]
Wrong CTFNote, https://github.com/TFNS/CTFNote. This project was started a couple weeks ago, the other one that i linked to was started 4 days ago. Frontend is also made in two different frameworks, and backend using different databases.
